version: '2.2'

services:

  ros2-zed:
    network_mode: "host"
    image: ros2:zed
    container_name: zed-camera-foxy
    healthcheck:
      test: ["CMD", "bash", "-c", ". /workspace/install/setup.bash; ros2 node list | grep -q /zed2/zed_node"]
      start_period: 1m
      interval: 5s
      timeout: 1s
      retries: 300
    build:
      network: host
      context: ./Docker
      dockerfile: ./Dockerfile_zed_foxy.dockerfile
      args:
        IMAGE_NAME: dustynv/ros:foxy-ros-base-l4t-r35.2.1

        # ROS
        ROS_DISTRO: foxy
        WORKSPACE: /workspace
        RMW_IMPLEMENTATION_INSTALL: rmw-cyclonedds-cpp
        RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
        ROS_DOMAIN_ID: 7
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions

    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        . install/setup.bash && 
        RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=7 ros2 launch zed_wrapper zed2.launch.py publish_tf:=false
      "

  noetic:
    # image: lucyannofrota/jetson:noetic #p3dx:noetic
    container_name: jetson-noetic
    extends:
      file: docker-compose-p3dx.yml
      service: noetic
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"

  noetic_foxy:
    # image: lucyannofrota/jetson:noetic-foxy #p3dx:noetic-foxy
    container_name: jetson-noetic-foxy
    extends:
      file: docker-compose-p3dx.yml
      service: noetic_foxy
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"


  noetic_p3dx:
    # image: lucyannofrota/p3dx:noetic #p3dx:noetic
    container_name: p3dx-noetic
    extends:
      file: docker-compose-p3dx.yml
      service: noetic_p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"

  noetic_foxy_p3dx:
    # image: lucyannofrota/p3dx:noetic-foxy #p3dx:noetic-foxy
    container_name: p3dx-noetic-foxy
    extends:
      file: docker-compose-p3dx.yml
      service: noetic_foxy_p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"
