version: '2.2'

services:

  smap-sampler-zed:
    network_mode: "host"
    image: smap:sampler-zed
    container_name: sampler-zed
    build:
      network: host
      context: ./Docker
      dockerfile: ./smap_sampler_zed.dockerfile
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions

    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        tail -f /dev/null
      "
    # . install/setup.bash

  smap-env:
    image: smap:env
    container_name: ros2-env
    build:
      network: host
      context: ./Docker
      dockerfile: ./smap.dockerfile
      args:

        BUILD_BASE_IMAGE: dustynv/ros:foxy-desktop-l4t-r35.2.1
        BUILD_IMAGE_NAME: smap:env
        L4T_VERSION: R35.2.1
        UBUNTU_VERSION: 20.04
        # ROS
        ROS_DISTRO: foxy
        WORKSPACE: /workspace
        # RMW_IMPLEMENTATION_INSTALL: rmw-cyclonedds-cpp
        # RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions

    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        tail -f /dev/null
      "