version: '2.2'

services:

  noetic_p3dx:
    image: pbuild:3dx-noetic
    container_name: p3dx-noetic-dev
    build:
      network: host
      context: ./Docker
      dockerfile: ./p3dx.dockerfile
      target: p3dx
      args:
        BUILD_BASE_IMAGE: build:jetson-noetic
        BUILD_IMAGE_NAME: p3dx-noetic

        # ROS
        WORKSPACE: /workspace

        # Entrypoint
        ENTRYPOINT_FILE: entrypoints/p3dx_entrypoint.bash

  noetic_foxy_p3dx:
    image: build:p3dx-noetic-foxy
    container_name: p3dx-noetic-foxy-dev
    build:
      network: host
      context: ./Docker
      dockerfile: ./p3dx.dockerfile
      target: e_stop
      args:
        BUILD_BASE_IMAGE: build:jetson-noetic-foxy
        BUILD_IMAGE_NAME: p3dx-noetic-foxy

        # ROS
        WORKSPACE: /workspace

        # Entrypoint
        ENTRYPOINT_FILE: entrypoints/p3dx_entrypoint.bash

  p3dx_navigation:
    image: p3dx-navigation
    container_name: p3dx-navigation-dev
    build:
      network: host
      context: ./Docker
      dockerfile: ./p3dx_navigation.dockerfile
      args:
        BUILD_BASE_IMAGE: dustynv/ros:foxy-desktop-l4t-r35.2.1
        BUILD_IMAGE_NAME: p3dx-navigation
        L4T_VERSION: R35.2.1
        UBUNTU_VERSION: 20.04
        # ROS
        ROS_DISTRO: foxy
        WORKSPACE: /workspace

        # Entrypoint
        ENTRYPOINT_FILE: entrypoints/p3dx_entrypoint.bash
