version: '2.2'

services:

  ros2-zed:
    network_mode: "host"
    image: build:zed
    container_name: zed-camera-foxy
    build:
      network: host
      context: ./Docker
      dockerfile: ./Dockerfile_zed_foxy.dockerfile
      args:
        IMAGE_NAME: dustynv/ros:foxy-ros-base-l4t-r35.2.1

        # ROS
        ROS_DISTRO: foxy
        WORKSPACE: /workspace
        RMW_IMPLEMENTATION_INSTALL: rmw-cyclonedds-cpp
        RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions

    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        tail -f /dev/null
      "
    # . install/setup.bash

  noetic:
    image: build:jetson-noetic #p3dx:noetic
    container_name: jetson-noetic
    extends:
      file: docker-compose-jetson.yml
      service: noetic
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"

  noetic_foxy:
    image: build:jetson-noetic-foxy #p3dx:noetic-foxy
    container_name: jetson-noetic-foxy
    extends:
      file: docker-compose-jetson.yml
      service: noetic_foxy
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"

  noetic_p3dx:
    image: build:p3dx-noetic #p3dx:noetic
    extends:
      file: docker-compose-p3dx.yml
      service: noetic_p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"

  noetic_foxy_p3dx:
    image: build:p3dx-noetic-foxy #p3dx:noetic-foxy
    extends:
      file: docker-compose-p3dx.yml
      service: noetic_foxy_p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"

  smap-sampler-zed:
    extends:
      file: docker-compose-smap.yml
      service: smap-sampler-zed

  smap-env:
    extends:
      file: docker-compose-smap.yml
      service: smap-env

  p3dx_navigation:
    extends:
      file: docker-compose-p3dx.yml
      service: p3dx_navigation

  smap-yolov5:
    extends:
      file: docker-compose-smap.yml
      service: smap-yolov5

  smap-deploy:
    extends:
      file: docker-compose-smap.yml
      service: smap-deploy

  # jetson-gpio:
  #   extends:
  #     file: docker-compose-jetson.yml
  #     service: jetson-gpio