version: '2.2'

# BUILD_BASE_IMAGE: lucyannofrota/

services:
 
  noetic:
    image: jetson:noetic
    container_name: jetson-noetic
    build:
      network: host
      context: ./Docker
      dockerfile: ./noetic_base.dockerfile
      target: noetic
      args:
        BUILD_BASE_IMAGE: nvcr.io/nvidia/l4t-base:r35.2.1
        BUILD_IMAGE_NAME: jetson:noetic
        UBUNTU_VERSION: 20.04
        L4T_VERSION: R35.2.1

        # ROS
        ROS1_DISTRO: noetic
        ROS1_BUILD: /ROS_NOETIC
        WORKSPACE: /workspace
        ROS_MASTER_URI: http://localhost:11311

        ENTRYPOINT: entrypoints/jetson_entrypoint.bash

  noetic_foxy:
    image: jetson:noetic-foxy
    container_name: jetson-noetic-foxy
    build:
      network: host
      context: ./Docker
      dockerfile: ./noetic_foxy.dockerfile
      target: noetic-foxy
      args:
        BUILD_BASE_IMAGE: lucyannofrota/jetson:noetic
        BUILD_IMAGE_NAME: jetson:noetic-foxy

        # ROS2
        ROS1_DISTRO: noetic
        ROS2_DISTRO: foxy
        WORKSPACE: /workspace
        RMW_IMPLEMENTATION_INSTALL: rmw-cyclonedds-cpp
        RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
        ROS_DOMAIN_ID: 7

        # Entrypoint
        ENTRYPOINT: entrypoints/jetson_entrypoint.bash

  noetic_p3dx:
    image: p3dx:noetic
    container_name: p3dx-noetic
    build:
      network: host
      context: ./Docker
      dockerfile: ./p3dx.dockerfile
      target: p3dx
      args:
        BUILD_BASE_IMAGE: lucyannofrota/jetson:noetic
        BUILD_IMAGE_NAME: p3dx:noetic

        # ROS
        WORKSPACE: /workspace

        # Entrypoint
        ENTRYPOINT: entrypoints/p3dx_entrypoint.bash

  noetic_foxy_p3dx:
    image: p3dx:noetic-foxy
    container_name: p3dx-noetic-foxy
    build:
      network: host
      context: ./Docker
      dockerfile: ./p3dx.dockerfile
      target: p3dx
      args:
        BUILD_BASE_IMAGE: lucyannofrota/jetson:noetic-foxy
        BUILD_IMAGE_NAME: p3dx:noetic-foxy

        # ROS
        WORKSPACE: /workspace

        # Entrypoint
        ENTRYPOINT: entrypoints/p3dx_entrypoint.bash
