version: '2.2'

services:
 
  jetson_noetic:
    image: jetson:noetic
    container_name: jetson-noetic
    build:
      network: host
      context: ./Docker
      dockerfile: ./Dockerfile_ros1_bridge.dockerfile
      target: noetic
      args:
        BASE_IMAGE: nvcr.io/nvidia/l4t-base:r35.2.1
        IMAGE_NAME: jetson:noetic
        UBUNTU_VERSION: 20.04
        L4T_VERSION: R35.2.1

        # ROS
        ROS1_DISTRO: noetic
        ROS1_BUILD: /ROS_NOETIC
        WORKSPACE: /workspace

  jetson_noetic_foxy:
    image: jetson:noetic-foxy
    container_name: jetson-noetic-foxy
    build:
      network: host
      context: ./Docker
      dockerfile: ./Dockerfile_ros1_bridge.dockerfile
      target: noetic-foxy
      args:
        BASE_IMAGE: lucyannofrota/jetson:noetic
        IMAGE_NAME: jetson:noetic-foxy
        UBUNTU_VERSION: 20.04
        L4T_VERSION: R35.2.1

        # ROS
        ROS1_DISTRO: noetic
        ROS2_DISTRO: foxy
        ROS1_BUILD: /ROS_NOETIC
        ROS2_BUILD: /ROS_FOXY
        WORKSPACE: /workspace

        # ROS2 parameters
        RMW_IMPLEMENTATION_INSTALL: rmw-cyclonedds-cpp
        RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
        ROS_DOMAIN_ID: 7

        # Entrypoint
        ENTRYPOINT_HOST_PATH: entrypoints/jetson_entrypoint.bash

  jetson_noetic_foxy_bridge:
    image: jetson:noetic-foxy-bridge
    container_name: jetson-noetic-foxy-bridge
    build:
      network: host
      context: ./Docker
      dockerfile: ./Dockerfile_ros1_bridge.dockerfile
      target: noetic-foxy-bridge
      args:
        BASE_IMAGE: lucyannofrota/jetson:noetic-foxy
        IMAGE_NAME: jetson:noetic-foxy-bridge
        UBUNTU_VERSION: 20.04
        L4T_VERSION: R35.2.1

        WORKSPACE: /workspace
        ROS_MASTER_URI: http://localhost:11311

